sudo: required
dist: trusty
language: cpp
os: osx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-2.0
  - sudo apt-get install -qq libsdl2-dev
  - sudo apt-get install -qq libsdl2-ttf-dev
  - sudo apt-get install -qq libsdl2-mixer-dev
  - sudo apt-get install -qq libpthread-stubs0-dev
  - sudo apt-get install -qq libgtest-dev
  - sudo apt-get install -qq google-mock

script:
  - make
  - make test
  - ./test

compiler:
  - g++
