language: cpp

before_install:
- sudo apt-get install -y  libsdl2-dev
- sudo apt-get install -y  libsdl2-mixer-dev
- sudo apt-get install -y  libsdl2-ttf-dev

script:
  - make
  - make test
  - ./test

compiler:
  - g++
