sudo: required
os: osx
language: cpp

before_install:
  - brew install sdl2
  - brew install sdl2_ttf
  - brew install sdl2_mixer
  - git clone https://github.com/google/googletest
  - cd googletest
  - mkdir build
  - cd build
  - cmake ..
  - make && make install
  - cd ../..

script:
  - make
  - make test
  - ./test

compiler:
  - g++
