language: cpp

before_install:
- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-get install -y  libsdl2-dev

script:
  - make game

compiler:
  - g++
