language: cpp

before_install:
  - sudo apt-get install libsdl2-2.0
  - sudo apt-get install libsdl2-dev
  - sudo apt-get install libsdl2-ttf-dev
  - sudo apt-get install libsdl2-mixer-dev
  - sudo apt-get install libpthread-stubs0-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install -y google-mock

script:
  - make
  - make test
  - ./test

compiler:
  - g++
